Document: dlauncher
Title: Debian dlauncher Manual
Author: <insert document author here>
Abstract: This manual describes what dlauncher is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dlauncher/dlauncher.sgml.gz

Format: postscript
Files: /usr/share/doc/dlauncher/dlauncher.ps.gz

Format: text
Files: /usr/share/doc/dlauncher/dlauncher.text.gz

Format: HTML
Index: /usr/share/doc/dlauncher/html/index.html
Files: /usr/share/doc/dlauncher/html/*.html
